#!/bin/sh
#
# Script to be included in the cadabra.deb package and to be run 
# after installation, to make TeX pick up our style sheets.

texhash
gtk-update-icon-cache-3.0 -t ${PREFIX}/share/icons/hicolor
