.TH CADABRA-SERVER 1 "Jan 22, 2019" "" ""
.\"
.\" Man page written by Kasper Peeters <info@cadabra.science>
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAME
cadabra-server \- the server backend for running Cadabra2 notebooks
.SH SYNOPSIS
.BR "cadabra-server"
.SH DESCRIPTION
.B On starting cadabra-server, it will print a port number on stdout, where
connections to the cadabra kernel can be made. All interaction with
the server is through that port on the localhost interface.

.SH SEE ALSO
.BR cadabra2-gtk (1), cadabra2 (1)

See the web page at
.BR "https://cadabra.science/"
for more information and up\-to\-date sample notebooks.
.SH AUTHORS
Kasper Peeters <info@cadabra.science>

