.TH CADABRA2PYTHON 1 "Jan 22, 2019" "" ""
.\"
.\" Man page written by Kasper Peeters <info@cadabra.science>
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 3 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAME
cadabra2python \- convert Cadabra2 text input files to pure Python
.SH SYNOPSIS
.BR "cadabra2python [cadabra input file (.cdb)] [python filename]"
.SH DESCRIPTION
.B The input format for cadabra2 is a special mixture of Cadabra2
notation and Python code. The cadabra2python command converts these
input files to pure Python files, which can be processed by
Python directly.

.SH SEE ALSO
.BR cadabra2 (1).

See the web page at
.BR "https://cadabra.science/"
for more information and up\-to\-date sample notebooks.
.SH AUTHORS
Kasper Peeters <info@cadabra.science>

