if(WIN32)
  windows_find_library(GLIBMM3_LIBRARIES REQUIRED glibmm sigc glib pcre gobject)
  if (GLIBMM3_LIBRARIES)
    set(GLIBMM3_FOUND TRUE)
  endif()
else()
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(GLIBMM3 REQUIRED glibmm-2.4)
  include_directories(${GLIBMM3_INCLUDE_DIRS})
  link_directories(${GLIBMM3_LIBRARY_DIRS})
  add_definitions(${GLIBMM3_CFLAGS_OTHER})
endif()

if (GLIBMM3_FOUND)
  message(STATUS "Found glibmm")
endif()