if(WIN32)
  find_path(SQLITE3_INCLUDE_DIRS sqlite3.h HINTS ${SQLITE3_ROOT}\\include\\sqlite3)
  find_library(SQLITE3_LIBRARIES sqlite3 HINTS ${SQLITE3_ROOT}\\lib)
  if(${SQLITE3_INCLUDE_DIRS} STREQUAL "")
    message(FATAL_ERROR "Could not find sqlite3!")
  endif()
  include_directories(${SQLITE3_INCLUDE_DIRS})
else()
  find_library(sqlite3 sqlite3 REQUIRED)
endif()
message("-- Found sqlite3 ${SQLITE3_LIBRARIES}")